name: Update Language Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Ejecutar todos los días a medianoche
  push:
    branches:
      - main

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install requests

      - name: Run language stats script
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: python script.py

      - name: Update README.md with language stats
        run: |
          sed -i '/<!-- Insertar el contenido de languages_stats.md aquí -->/r languages_stats.md' README.md
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Update README.md with latest language stats'
          git push
